name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository
    - name: Checkout Current Repository
      uses: actions/checkout@v3

    # Example step to list files in the repository
    - name: List files in the repository
<<<<<<< HEAD
      run: ls -la
=======
      run: ls -la
>>>>>>> 67b369d21ee43e009b38b90ff8c6938b3a0b5ebd
